// packages/vue-mobile-template/src/App.vue
<template>
  <div id="app">
    <router-view></router-view>
  </div>
</template>
<script>
export default {
  beforeUpdate () {
    this.hideLoading()
  },
  methods: {
    hideLoading () {
      document.getElementById('y-loading').style.display = 'none'
    }
  }
}
</script>

<style lang="scss" scoped>
@import './styles/common/var.scss';
#app {
  min-height: 100vh;
  width: 100vw;
  height: 100vh;
  background-color: $bg-color;
}
</style>

// packages/react-mobile-template/src/App.js
import React from 'react'
import RouterView from './router'

class App extends React.Component {
  componentDidMount () {
    this.hideLoading()
  }

  hideLoading () {
    document.getElementById('y-loading').style.display = 'none'
  }

  render () {
    return (
      <div id="App">
        <RouterView></RouterView>
      </div>
    )
  }
}

export default App
